# Generated by Django 2.2.4 on 2020-12-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(default='normal', max_length=50),
            preserve_default=False,
        ),
    ]
